# -*- coding: utf-8 -*-
"""Copy of Lab3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y1k_SkDdJYsyYRvqBdf1phzUIRxs_RRE

## MATH 151 Lab  3

Put team members' names and section number here.
"""

from sympy import *
from sympy.plotting import (plot,plot_parametric)

"""### Question 1"""

print('the IVT says that for any value given in a continuous function, there lies a real point on the function')
print('f has a root between 1 and 0 because f(0) is neg. and f(1) is pos.')

"""#### 1a"""

x=symbols('x')

f = (x**5)+(4*x**3)-(2*x**2)+(8*x-1)

f_0 = f.subs(x,0)
print('f(0) =', f_0)

f_1 = f.subs(x,1)
print('f(1) =', f_1)

"""#### 1b"""

print('the root of the function inside [0,1] is', nsolve(f,x,0))

"""### Question 2

#### 2a
"""

f1 = 2*x-3
f2 = 4*x-x**2
f3 = (x**2-6*x+8)/(x-4)
f4 = exp(((x-4)*(log(3))))

fo3_1h1 = limit(f1,x,3)
fo3_rh1 = limit(f2, x, 3)


print("lim of f(1) from left", fo3_1h1)
print("lim of f(1) from right", fo3_rh1)

"""#### 2b"""

plot( 2*x-3,4*x-x**2,(x**2-6*x+8)/(x-4),exp(((x-4)*(log(3))))   )

"""### Question 3

#### 3a
"""

#graph

#limit

"""#### 3b"""

#graph

#limit

"""#### 3c"""

#graph

#limit

"""#### 3d"""

#observation on K